---
version: '2'

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "5002:5000"
    environment:
      DB_NAME: /data/db
    volumes:
      - db-volume:/data/
    depends_on:
      - broker
      - fluent

  listener:
    build:
      context: .
      dockerfile: listener.Dockerfile
    environment:
      DB_NAME: /data/db
    volumes:
      - db-volume:/data/
    depends_on:
      - broker
      - fluent

  broker:
    image: eclipse-mosquitto:1.4.12
    ports:
      - "9001:9001"
      - "1883:1883"
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"

  fluent:
    image: fluent/fluentd
    ports:
      - "24224:24224"
    volumes:
      - "./fluent.conf:/fluentd/etc/fluent.conf"

volumes:
  db-volume:
