---
version: "2.4"

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "5002:5000"
    environment:
      DB_NAME: /data/db
    volumes:
      - db-volume:/data/
    depends_on:
      - broker
      - fluent

  listener:
    build:
      context: .
      dockerfile: listener.Dockerfile
    environment:
      DB_NAME: /data/db
    volumes:
      - db-volume:/data/
    depends_on:
      - broker
      - fluent

  broker:
    image: eclipse-mosquitto:2.0.15
    ports:
      - "9001:9001"
      - "1883:1883"
    volumes:
      - target: /mosquitto/config/mosquitto.conf
        source: ./mosquitto.conf
        type: bind
        read_only: true
      - target: /mosquitto/config/mosquitto_passwd
        source: ./mosquitto_passwd
        type: bind
        read_only: true

  fluent:
    image: fluent/fluentd:v1.16
    ports:
      - "24224:24224"
    volumes:
      - "./fluent.conf:/fluentd/etc/fluent.conf"

volumes:
  db-volume:
