---

test_name: Test trying to subscribe with a too-large qos fails

includes:
  - !include common.yaml

paho-mqtt: &mqtt_spec
  auth:
    username: tavern
    password: tavern
  # tls:
  #   enable: true
  connect:
    host: localhost
    port: 9001
    timeout: 3
  client:
    transport: websockets
    client_id: tavern-tester

_xfail: verify

stages:
  - &setup_device_for_test
    name: create device
    request:
      url: "{host}/create_device"
      method: PUT
      json:
        device_id: "{random_device_id}"
        clean: True
    response:
      status_code: 201

  - name: step 1 - ping/pong
    mqtt_publish:
      topic: /device/123/ping
      payload: ping
    mqtt_response:
      topic: /device/123/pong
      payload: pong
      timeout: 5
      qos: 3

---

test_name: Test trying to subscribe with an invalid qos fails

includes:
  - !include common.yaml

paho-mqtt: *mqtt_spec

_xfail: verify

stages:
  - *setup_device_for_test

  - name: step 1 - ping/pong
    mqtt_publish:
      topic: /device/123/ping
      payload: ping
    mqtt_response:
      topic: /device/123/pong
      payload: pong
      timeout: 5
      qos: weefwe

---

test_name: Test trying to connect with an invalid username/password fails

includes:
  - !include common.yaml

_xfail: run

paho-mqtt:
    <<: *mqtt_spec
    auth:
      username: tavern
      password: hhehehehh

stages:
  - *setup_device_for_test

  - name: Echo json
    mqtt_publish:
      topic: /device/{random_device_id}/echo
      json:
        message: hello world
    mqtt_response:
      topic: /device/{random_device_id}/echo/response
      json:
        message: hello world
      timeout: 5
      qos: 1

---

test_name: Test incorrect type token fails

includes:
  - !include common.yaml

paho-mqtt: *mqtt_spec

_xfail: run

stages:
  - *setup_device_for_test

  - name: Test checking for lights status with anystr fails
    mqtt_publish:
      topic: /device/123/status
    mqtt_response:
      topic: /device/123/status/response
      json:
        lights: !anystr
      timeout: 3
      qos: 1

---

test_name: Test expecting empty payload but receiving a payload fails

includes:
  - !include common.yaml

paho-mqtt: *mqtt_spec

_xfail: run

stages:
  - *setup_device_for_test

  - name: Test checking for lights status with anyint
    mqtt_publish:
      topic: /device/123/status
    mqtt_response:
      topic: /device/123/status/response
      timeout: 3
      qos: 1

---

test_name: Test unexpected message fails

includes:
  - !include common.yaml

paho-mqtt: *mqtt_spec

_xfail: run

stages:
  - *setup_device_for_test

  - name: step 1 - ping/pong
    mqtt_publish:
      topic: /devices/status
    mqtt_response:
      - topic: /device/456/status/response
        payload: !anything
        timeout: 2
        qos: 1
        unexpected: true
      - topic: /device/{random_device_id}/status/response
        payload: !anything
        timeout: 2
        qos: 1
        unexpected: true

---

test_name: Test unexpected message fails even on its own

includes:
  - !include common.yaml

paho-mqtt: *mqtt_spec

_xfail: run

stages:
  - *setup_device_for_test

  - name: step 1 - ping/pong
    mqtt_publish:
      topic: /devices/status
    mqtt_response:
      - topic: /device/88466412/status/response
        payload: !anything
        timeout: 3
        qos: 1
        unexpected: true
