repos:
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.11
    hooks:
      - id: actionlint
        args: ["-shellcheck="]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.15.8
    hooks:
      - id: ruff-format
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [yaml]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - "types-protobuf>=5,<6"
          - types-PyYAML
          - mypy-extensions
        exclude: tests
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.11.2
    hooks:
      - id: uv-lock
  - repo: local
    hooks:
      - id: starlark-docstring-markdown
        name: starlark-docstring-markdown
        entry: uv
        args:
          - tool
          - run
          - git+https://github.com/michaelboulton/starlark-docstring-markdown@df06acc9307e9ad8bd83fe618f012072f288d3d1
          - tavern/tavern/_core/starlark/
          - tavern/docs/source/scripting-api.md
        language: system
        pass_filenames: false
        files: \.star$

exclude: (docs/|example/)
